name = "NumericalTools"
uuid = "a0f06128-cd74-4043-ac90-c71291fe1646"
authors = ["Chen Xia <xiachen1996@outlook.com> and contributors"]
version = "0.1.1"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[compat]
Interpolations = "0.14.2"
julia = "1.6.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
